### ISSUE TITLE
Who should participate in the survey

### ISSUE THREAD

**Issue by gedankenstuecke** [aath0/MinoritiesInResearch#14]
While discussing that the demographics should come at the end of the survey we thought about who should be invited to participate in the study. 

We thought that also non-URM-members can take at least part of the survey: The personal experience of participating in a study would be asked only for ppl who identify as member of the URM community, while the 'have you heard about studies in the media etc.' parts would be open for everyone, this could potentially show some very different opinions between URM/non-URM participants.

**Comment by aath0** [comment]
Okay, I've now updated that!
Please find the latest version here:
https://www.soscisurvey.de/URM_pilot/index.php?i=IW1758YBVLGI&rnd=AILC
