### ISSUE TITLE
Specify key directions we want to address

### ISSUE THREAD

**Issue by aath0** [aath0/MinoritiesInResearch#3]
First big question: which directions do we want that our survey takes?? The initial idea is to see if members of URM:
* Are interested and informed about research that concerns them
* Find this research: Respectful / Useful / Interesting

Any other ideas?

**Comment by gedankenstuecke** [comment]
We could potentially split the survey in *having heard about such research* and *having participated in such research*, to see whether there's some difference between people who hear about research and those who participate. I made some potential ideas up in #6.

**Comment by gedankenstuecke** [comment]
Solved at Mozfest! 🎉
