### ISSUE TITLE
Adding us to open leadership zone for #mozfest

### ISSUE THREAD

**Issue by gedankenstuecke** [aath0/MinoritiesInResearch#8]
We should submit this to the [*Open Leadership Zone*](https://github.com/acabunoc/open-leadership-zone#getting-started) for Mozfest. 

To do so we would 
* need to [create an issue here](https://github.com/acabunoc/open-leadership-zone/issues/new),
* Tick all the boxes that are part of the issue. The only thing we're missing right now is a `LICENSE` (but see #7),
* [submit to Pulse](https://www.mozillapulse.org/add),
* and tell Abby that we're ready by commenting on the issue we created above. 

Sounds good?

**Comment by abbycabs** [comment]
YOU'RE IN! 🎉 https://www.mozillapulse.org/entry/502

**Comment by gedankenstuecke** [comment]
Awesome, thanks so much @acabunoc!
